### ISSUE TITLE
Subtitles?

### ISSUE THREAD

**Issue by siracusa** [dmthomas/AppleVideoDownloadScripts#1]
Do you know of a way to get subtitle tracks for the videos?

**Comment by dmthomas** [comment]
Working on it. I'll update the scripts when it's ready.

**Comment by siracusa** [comment]
Awesome, thanks!

**Comment by dmthomas** [comment]
I updated Tuesday's sessions to add subtitles. I'll go back and do the subtitles for Monday (that's manual, I don't have a tool that generates the script for those.)

Let me know if the subtitles don't work for some reason. I tested them in QuickTime Player, Iina, VLC, Infuse, and Plex.
